### ISSUE TITLE
Shutdown vm action  doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-templates#117]
## Issue 
use shutdown action on VM, nothing happen and state of vm still running. 

## Blueprint 
```
services:

  - github.com/zero-os/0-templates/vm/0.0.1__c201c70b:
      flist: https://hub.gig.tech/gig-bootable/ubuntu:16.04.flist
      nics:
        - name: 0226f83f
          type: default

actions:
  - template: github.com/zero-os/0-templates/vm/0.0.1
    actions: ['shutdown']
    service: c201c70b

```
