### ISSUE TITLE
A container has been created on an existing node although a fake node was provided. 

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-templates#82]
## Scenario
1- Run a blueprint to create a container on a non-existing node  

## Blueprint 
```
services:
  - github.com/zero-os/0-templates/node/0.0.1__2009f1bb:
      redisPort: 6379
      redisAddr: 127.0.0.1
      hostname: myzeros

  - github.com/zero-os/0-templates/container/0.0.1__jojo6:
      flist: https://hub.gig.tech/gig-official-apps/ubuntu1604.flist
      hostname: jojo6
      storage: ardb://hub.gig.tech:16379
      node: 2342asdc

actions:
  - template: github.com/zero-os/0-templates/container/0.0.1
    actions: ['install']

  - template: github.com/zero-os/0-templates/node/0.0.1
    actions: ['install']

```

## Actual Results
1-  A node service has been created and it is connected to actual zero-os node N1 (2009f1bb)
2- The container has been created on N1(this shouldn't happen) and no errors on the zrobot server indicating that the node used - to create the container on - is not there.
3- Also the state in the tasks.yaml file is stuck in running state.

## tasks.yaml
```root@0-robot0:/opt/code/github/john-kheir/0-robot6/zrobot_data/github.com/zero-os/0-templates/container/jojo6/1c035948-3ba2-49c3-bc06-6806ce1e6078# cat tasks.yaml 
-   action_name: save
    args: null
    created: 1523964189
    eco: null
    guid: 62c8d475-ed13-4f69-aa17-f03822e6df91
    state: running
```
